version: '3'
services:
  postgresql:
    image: postgres:9.6
    volumes:
      - smartrural:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=smartrural
      - POSTGRES_USER=smartrural
      - POSTGRES_PASSWORD=smartrural
volumes:
  smartrural:
    external: false