# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build documentation and send email to notify - documentation-tfg

on:
  push:
    branches:
      - feature/documentation

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Memoria del TFG
        to: ${{secrets.MAIL_TO}}
        from: ${{secrets.MAIL_USERNAME}}
        secure: true
        html_body: file://INFO.md
        convert_markdown: true
        cc: ${{secrets.MAIL_CC}}
        ignore_cert: true
        attachments: LICENSE
