# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build documentation and send email to notify - documentation-tfg

on:
  push:
    branches:
      - feature/documentation
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Compile LaTeX documentation
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: documentation/
        root_file: main.tex

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'code.zip'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'code.zip'
        token: ${{secrets.GITHUB}}

    - uses: actions/upload-artifact@v1
      with:
        name: docs
        path: documentation

    - uses: actions/upload-artifact@v1
      with:
        name: code
        path: .

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Memoria y Código del TFG
        to: ${{secrets.MAIL_TO}}
        from: ${{secrets.MAIL_USERNAME}}
        secure: true
        html_body: file://INFO.md
        convert_markdown: true
        cc: ${{secrets.MAIL_CC}}
        ignore_cert: true
        attachments: LICENSE,documentation/main.pdf,code.zip
